### ISSUE TITLE
Unclear

### ISSUE THREAD

**Issue by SnazofSnaz** [learn-co-curriculum/javascript-arrays#15]
is the array I am adding elements to the choclate bars or am I creating an array to alter within the arrays.js

I just feel unclear as to what my target focus is for the material I am learning for learning this material. I think that requires more extrapolation than the lesson intends. I notice that happens with previous lesson as well...

Is encouraging like - ok now go, but, its just like; 
I should be editing chocolate bars var?

Like is not the content that is confusing to me from this - its the directing of my intention for applying that information that I find myself confused... Perhaps that is what I am to expect as an independent freelancer or from a bootcamp.. Its just a little daunting at hour two to feel so confused as to how to accomplish what is asked of me...

I should add its not the entire lesson; an I notice a striving to explain solution etc.. I just still feel like I did a lot better with the ok, lets try this one together - an then off you go.

Now I'm like ok... What is it I am destroying an element of?

**Comment by AnnJohn** [comment]
hi @SnazofSnaz we do make these lessons challenging intentionally. We give you just enough to set out on solving the lab, but we also expect that you'll google and try to figure things out on your own. A large part of a developer's day is googling and learning how to learn and learning how to google is important. 

Also we have Ask a Question in Learn that you can use at any time and when you do, someone will help you out in real time. So you can go ahead and ask your question- what are you destroying an element of- there. Thanks!
