### ISSUE TITLE
There is no test for destructivelyRemoveElementFromBeginningOfArray

### ISSUE THREAD

**Issue by farrelld09** [learn-co-curriculum/javascript-arrays#17]
In the arrays-test.js file, there is no test for the function destructivelyRemoveElementFromBeginningOfArray

...Even though the ReadMe file and learn.co both instruct the student to create the function.  Just thought I'd let you know!

-Dan

**Comment by farrelld09** [comment]
Actually the test for destructivelyRemoveElementFromEndOfArray is also missing.

**Comment by 0KayPi** [comment]
Just a short heads up that the issue still persists

**Comment by gj** [comment]
Closed in #50. Thanks @farrelld09 !
