### ISSUE TITLE
ask a question tab

### ISSUE THREAD

**Issue by bercohen** [learn-co-curriculum/javascript-arrays#21]
i was in the middle of discussing a question and i had to refresh my page do to internet and now my "ask a question" tab is not working

**Comment by aturkewi** [comment]
Hey @bercohen I'm sorry I'm so late seeing this. We definitely do not want this to happen. 
Given that some time has passed since this issue was raised, could you take another look and see if it's back working?

I'm going to close this for now, but feel free to re-open if you still need a hand.
