### ISSUE TITLE
Lesson description not correct

### ISSUE THREAD

**Issue by 7022Andre** [learn-co-curriculum/javascript-arrays#26]
Functions destructivelyRemoveElementFromBeginningOfArray and destructivelyRemoveElementFromEndOfArray are not defined in array-test.js.
TODO's for these functions ("should mutate array") should reflect correct functions and be renamed to removeElementFromBeginningOfArray and removeElementFromEndOfArray.

Remove TODO's ("should **NOT** mutate array") for functions removeElementFromBeginningOfArray and removeElementFromEndOfArray because these specific tests are not included in array-test.js.

**Comment by esugano** [comment]
I have the same problem

**Comment by aturkewi** [comment]
Fixed with PR #34
