### ISSUE TITLE
Complainy, I know, but this lesson is obscenely long.

### ISSUE THREAD

**Issue by eggnogdog1** [learn-co-curriculum/javascript-arrays#38]
I am having a serious organizational problem managing this lesson. It's difficult to go in between screens (applications). I'm also lucky to be on a retina mac! Can't imagine doing this one a 1080p screen. 

This is the first lesson of all lessons (from the beginning of Javascript) that is this long. It is cumbersome and distracts from the learning concepts. I don't think arrays are any more complicated that scopes yet this lesson is just far less manageable. It should be divided into several lessons. It may be less elegant in the outline, but it will be easier for students to navigate and process. Sorry to complain-- this is a solvable problem for me bc i have a second monitor, but I think it will really negatively affect some people.

**Comment by FernanGonzalez** [comment]
I agree. Besides, once you finish the exercise, you just want to click "Next lesson". It's a pity they didn't divide it into more lessons.
