### ISSUE TITLE
Consistent Error Message

### ISSUE THREAD

**Issue by ppreyer** [learn-co-curriculum/javascript-arrays#39]
I'm receiving a consistent error for the Javascript Arrays lab.  I've tried uninstalling and restarting my Learn app with no success.  I've also tried deleting the arrays.js file and creating a new one.  The error message is below:

This directory doesn't appear to have any specs in it.

Any help on resolving this issue would be greatly appreciated.

**Comment by JessRudder** [comment]
Hi @ppreyer if you're still having this issue, please use the "Ask a Question" feature on the right side of Learn to get live help from a Learn Expert.
