### ISSUE TITLE
Misleading instructions for removeElementFromEndOfArray function

### ISSUE THREAD

**Issue by FrederickWilliams** [learn-co-curriculum/javascript-arrays#42]
The Readme file instructs the student for `removeElementFromEndOfArray() `  

> TODO: Define a function in arrays.js called removeElementFromEndOfArray that takes an array as its only argument and removes the last element. Your function should return the entire array, and it should not mutate the array.

However, the test is looking for the slice of the array instead of, the entire array

**Comment by joshuabamboo** [comment]
+1 I think we could clarify the `Your function should return the entire array` part. It is not clear that they should be returning the result of `slice`, not the array that was passed in.

**Comment by gj** [comment]
Closed in #50. Thanks @FrederickWilliams !
