### ISSUE TITLE
Destructively Remove Element contradicts itself from IDE array-test.js

### ISSUE THREAD

**Issue by DanRios** [learn-co-curriculum/javascript-arrays#44]
The lesson reads that the function (destructivelyRemoveElementFromEndOfArray) should mutate. 

The array-test.js file contradicts what the lesson reads.

See attachments.

![screen shot 2017-08-08 at 2 11 55 pm](https://user-images.githubusercontent.com/17032026/29087784-24419640-7c45-11e7-81c7-4fb7eb6eca01.png)

![screen shot 2017-08-08 at 2 12 23 pm](https://user-images.githubusercontent.com/17032026/29087803-36b1d6b4-7c45-11e7-93a1-5a2acb74f660.png)

If the function is supposed to "destructively" remove, shouldn't it make a copy of the original?

**Comment by sgharms** [comment]
A destructive operation should change the original item and _not_ return a copy.

If the lab experience does not accord with this expectation, please update this issue.

Thanks! 💙
