### ISSUE TITLE
removeElementFromEndOfArray(array) test

### ISSUE THREAD

**Issue by ChadMichaelPro** [learn-co-curriculum/javascript-arrays#47]
removeElementFromEndOfArray(array) test allows you to pass using "array.splice(2)". Based on the text it looks like it should be forcing you to use "array = array.slice(0, array.length - 1)" instead.

**Comment by akaPadol** [comment]
couse the function isn't supposed to work only in a 3 element array, go throught with the step is a mess, a bug, splice(2) will remove everyting that is after the 2nd index, so doing that dosen't work with a 5 or 6 or n+1 element array with n > 3, array.lenght instad does

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue--it may have already been fixed, so I'm going to close it for now.

The test fails if `array.splice(2)` is used.

As always, thanks for contributing! 💙
