### ISSUE TITLE
todo vs solution vs tests

### ISSUE THREAD

**Issue by samnags** [learn-co-curriculum/javascript-arrays#5]
The TODO says to define a function called chocolateBars. However simply writing a function chocolateBars that returns the array doesn't work. The test wants you to write a variable chocolateBars that points to function returning array. As a side note, test also passes with a variable assigned to an array of chocolate bars, not a function

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by pletcher** [comment]
Ah, good catch! I updated the instructions -- looks like it should just be assigning an array to a variable.
