### ISSUE TITLE
Reference errors

### ISSUE THREAD

**Issue by zsiegel41** [learn-co-curriculum/javascript-arrays#51]
I believe I have the correct js code, but I get the following error when I test it:

arrays addElementToBeginningOfArray(array, element) adds an element to the beginning of an array:
     ReferenceError: addElementToBeginningOfArray is not defined

**Comment by drakeltheryuujin** [comment]
Hi there,

It looks like you've solved the lab. If you feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
