### ISSUE TITLE
I am just plain stuck

### ISSUE THREAD

**Issue by galnova** [learn-co-curriculum/javascript-arrays#52]
The errors aren't clear to me and I have been stuck on this for over a week. Someone helped earlier but it was not saved and nothing I try works. Can someone please get me out of this personal nightmare???

**Comment by asabogal** [comment]
exactly where are you stuck?

**Comment by drakeltheryuujin** [comment]
Thank you for providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this
issue. 💙
