### ISSUE TITLE
array lab 

### ISSUE THREAD

**Issue by jayveethebarber** [learn-co-curriculum/javascript-arrays#53]
ive been asking for help with the array lab for two days i received help on the first part but no help on the second part and its really starting to frustrate not because i dont understand but i not getting the answers to my questions

**Comment by drakeltheryuujin** [comment]
Hi there,

It looks like you've solved the lab. If you feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
