### ISSUE TITLE
Misleading removeElementFromBeginningOfArray instructions?

### ISSUE THREAD

**Issue by FernanGonzalez** [learn-co-curriculum/javascript-arrays#55]
> TODO: Define a function in arrays.js called removeElementFromBeginningOfArray that takes an array as its only argument and removes the first element. Your function should **then** return the entire array, and it should not mutate the underlying array.

It sounds like first, you remove the element with slice, and then, you return the entire array in another line. When the solution is:

```
function removeElementFromBeginningOfArray(array) {
  return array.slice(1)
}
```

I was stuck because of the wording.

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
