### ISSUE TITLE
Folders won't load...

### ISSUE THREAD

**Issue by aebenw** [learn-co-curriculum/javascript-arrays#57]
For some reason, the folders in CodePen won't load. The only one that will is array.js. I can't test my code ! I can't move on to the next lesson properly !

**Comment by drakeltheryuujin** [comment]
Thank you for feedback.
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
