### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by annieeby** [learn-co-curriculum/javascript-arrays#62]
This is not a real issue-flag, but a passing suggestion: you might take Elizabeth Holmes out of your example array of female entrepreneurs. Just as today you probably wouldn't create an array like
var attorneys = ["Michael Cohen", "Gloria Allred"]
or
var entertainers = ["Bill Cosby", "Brad Pitt"]
it's a bit strange to see Elizabeth Holmes listed as an entrepreneur among the likes of Laurene Powell Jobs and Arianna Huffington at this point.

**Comment by drakeltheryuujin** [comment]
We have updated the materials per your feedback.
Thank you for your feedback 💙
