### ISSUE TITLE
Happened again...totally erased my saved work

### ISSUE THREAD

**Issue by lerenah** [learn-co-curriculum/javascript-arrays#65]
<img width="1393" alt="screen shot 2018-12-09 at 3 58 15 pm" src="https://user-images.githubusercontent.com/32880751/49702841-4a670b00-fbcb-11e8-8884-c4638bf745bb.png">

It happened again.  This time, I thought that if I saved my work, I would be ok.  While finishing the module and reading down to the bottom, I received the "Oops" error and it completely erased my work.  I don't know.  There is definitely a glitch in this system as it keeps happening in every module.  

All of the functions that the module said to write were completely filled in and there was no yellow dot on top of this file.  My work was in fact saved, but now it is gone.  I am not trusting continuing to work in the IDE.  I might have to create my own files in VS Code.

**Comment by lerenah** [comment]
All of the functions that the module said to write were completely filled in and there was no yellow dot on top of this file.  My work was in fact saved, but now it is gone.

**Comment by maxwellbenton** [comment]
Hi @lerenah,

Sorry to hear that you lost work. This issue was due to a bug in Learn that should be resolved now. If you continue to experience this issue on future lessons, please feel free to reach out to support@learn.co for further assistance.

Thank you!
