### ISSUE TITLE
IDE Issues

### ISSUE THREAD

**Issue by daniemart5** [learn-co-curriculum/javascript-arrays#66]
I have been working on the JavaScript Arrays lab and I saved my work multiple times before I closed IDE. I closed it because I felt maybe my changes weren't being registered. When I reopened it all my work was gone. Sooo frustrating.

**Comment by maxwellbenton** [comment]
Hi @daniemart5,

Sorry to hear that your work was lost. This issue is due to a bug in Learn, and our engineering team has been notified. If you continue to experience this issue on future lessons, please feel free to reach out to support@learn.co for further assistance.

Thank you!
