### ISSUE TITLE
Method is called 'descructivelyAddElementToBeginningOfArray'

### ISSUE THREAD

**Issue by samnags** [learn-co-curriculum/javascript-arrays#7]
Should be 'destructively'. It's referred to as descructively in both readme and test

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by pletcher** [comment]
That's embarrassing -- thanks for catching that! Fixed in https://github.com/learn-co-curriculum/javascript-arrays/commit/58f631df60b4f1ac58f01b7a11c8c31c46900aee
